markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Roman's blog]
description: [Blog with my articles about different aspects of secure coding techniques for iOS/Android/React]
relative_links:
  enabled: true
  collections: true
